#195 tabs bugs
nus-mtp/steps-networking-module pull request #196
Opened 2017-03-18 15:11 UTC by Muhammad-Adam

closes #195

2017-03-18 17:07 UTC, ycewe requested changes
Please resolve conflict before I can merge

2017-03-18 17:07 UTC, ycewe commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
Have you tried running `gulp lint`? If I am not mistaken, it will give an error because you removed the comma at the end.

2017-03-18 17:09 UTC, Muhammad-Adam commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
Ouh my. I never run that before and there are alot of errors

2017-03-18 17:17 UTC, Muhammad-Adam commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
`const nowDate = new Date();`

They say this will give me the doublequote. How to overcome this?

2017-03-18 17:22 UTC, ycewe commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
Lol. I don't understand. But just google the lint error. Sure have it online.

2017-03-18 17:25 UTC, Muhammad-Adam commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
Almost 1k error. GG.

2017-03-18 17:28 UTC, ycewe commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
Solve all your errors. Check what files your edited.

2017-03-18 17:29 UTC, Muhammad-Adam commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
Nvm I do all the 1k errors

2017-03-18 17:54 UTC, Muhammad-Adam commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
I think cannot. Too many. I did all my side. Please check

2017-03-18 18:06 UTC, Muhammad-Adam commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
I dk how to resolve conflict leh. I never do before. :/

2017-03-18 18:32 UTC, ycewe commented on app/components/home/sampleData.js
> -    description: 'Party all night at Pasir Ris!',
Cause I don't know what you need and what you don't. You can use the link below or if you use source tree, just rebase.

2017-03-19 06:49 UTC, Muhammad-Adam commented
Changes done, please review.

2017-03-21 11:01 UTC, Muhammad-Adam commented
@ycewe im done. Please review

2017-03-22 05:15 UTC, merged